spring:
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.security: warn

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
